name: 'duckflix'
services:
    rqbit:
        image: ikatson/rqbit:latest
        container_name: duckflix_rqbit
        restart: always
        ports:
            - '3030:3030'
            - '6881:6881/tcp'
            - '6881:6881/udp'
        environment:
            - RQBIT_HTTP_LISTEN_ADDR=0.0.0.0:3030
            - RQBIT_DEFAULT_OUTPUT_FOLDER=/home/rqbit/downloads
        volumes:
            - rqbit_db:/home/rqbit/db
            - rqbit_cache:/home/rqbit/cache
            - ./data/temp/downloads:/home/rqbit/downloads
        networks:
            - duckflix_network

    server:
        image: ghcr.io/duckflixapp/duckflix:latest
        container_name: duckflix_backend
        restart: always
        init: true
        command: sh -c "bun run db:migrate && bun run start"
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
        volumes:
            - ./data:/app/data
            - ./logs:/app/logs
            - ./certs:/app/certs:ro
        tmpfs:
            - /app/data/live:size=4G,mode=1777
        networks:
            - duckflix_network
        logging:
            driver: json-file
            options:
                max-size: '10m'
                max-file: '3'

    web:
        image: ghcr.io/duckflixapp/duckflix-web:latest
        container_name: duckflix_frontend
        env_file:
            - .web.env
        restart: always
        ports:
            - '5173:80'
        networks:
            - duckflix_network

networks:
    duckflix_network:
        driver: bridge

volumes:
    rqbit_db:
    rqbit_cache:
